import type { MenuItemModel } from "./menu/menuItem.model";

export const menuData: MenuItemModel[] = [
	{
		id: "dashboard",
		text: "Dashboard",
		icon: "tachometer-alt",
		iconColor: "text-blue-400",
		isFolder: false,
		items: [],
	},
	{
		id: "finance",
		text: "Finance",
		icon: "money-bill",
		iconColor: "text-emerald-400",
		isFolder: true,
		items: [
			{
				id: "transactions",
				text: "Transactions",
				icon: "exchange-alt",
				iconColor: "text-indigo-400",
				isFolder: true,
				items: [
					{
						id: "all-transactions",
						text: "All",
						icon: "list",
						iconColor: "text-slate-400",
						isFolder: false,
						items: [],
					},
					{
						id: "incomes",
						text: "Incomes",
						icon: "arrow-up",
						iconColor: "text-green-400",
						isFolder: false,
						items: [],
					},
					{
						id: "expenses",
						text: "Expenses",
						icon: "arrow-down",
						iconColor: "text-rose-400",
						isFolder: false,
						items: [],
					},
				],
			},
			{
				id: "recurring",
				text: "Recurring",
				icon: "sync",
				iconColor: "text-purple-400",
				isFolder: true,
				items: [
					{
						id: "recurring-incomes",
						text: "Incomes",
						icon: "sync",
						iconColor: "text-teal-400",
						isFolder: false,
						items: [],
					},
					{
						id: "recurring-expenses",
						text: "Expenses",
						icon: "sync",
						iconColor: "text-pink-400",
						isFolder: false,
						items: [],
					},
				],
			},
			{
				id: "categories-budgets",
				text: "Categories & Budgets",
				icon: "tags",
				iconColor: "text-amber-400",
				isFolder: true,
				items: [
					{
						id: "categories",
						text: "Categories",
						icon: "tags",
						iconColor: "text-cyan-400",
						isFolder: false,
						items: [],
					},
					{
						id: "budgets",
						text: "Budgets",
						icon: "piggy-bank",
						iconColor: "text-emerald-400",
						isFolder: false,
						items: [],
					},
				],
			},
			{
				id: "accounts",
				text: "Accounts & Wallets",
				icon: "university",
				iconColor: "text-sky-400",
				isFolder: true,
				items: [
					{ id: "cash", text: "Cash", icon: "money-bill", iconColor: "text-lime-400", isFolder: false, items: [] },

					{
						id: "cards",
						text: "Cards",
						icon: "credit-card",
						iconColor: "text-fuchsia-400",
						isFolder: false,
						items: [],
					},
				],
			},
		],
	},
	{
		id: "products",
		text: "House Products",
		icon: "box",
		iconColor: "text-orange-400",
		isFolder: true,
		items: [
			{ id: "inventory", text: "Inventory", icon: "boxes", iconColor: "text-stone-400", isFolder: false, items: [] },
			{
				id: "expiring-soon",
				text: "Expiring Soon",
				icon: "hourglass-half",
				iconColor: "text-red-400",
				isFolder: false,
				items: [],
			},
			{
				id: "locations",
				text: "Locations",
				icon: "map-marker-alt",
				iconColor: "text-amber-400",
				isFolder: true,
				items: [
					{ id: "fridge", text: "Fridge", icon: "snowflake", iconColor: "text-sky-400", isFolder: false, items: [] },
					{
						id: "freezer",
						text: "Freezer",
						icon: "snowflake",
						iconColor: "text-blue-400",
						isFolder: false,
						items: [],
					},
					{
						id: "pantry",
						text: "Pantry",
						icon: "box-open",
						iconColor: "text-yellow-500",
						isFolder: false,
						items: [],
					},
					{
						id: "bathroom",
						text: "Bathroom",
						icon: "tint",
						iconColor: "text-purple-400",
						isFolder: false,
						items: [],
					},
				],
			},
		],
	},
	{
		id: "reports",
		text: "Reports",
		icon: "chart-line",
		iconColor: "text-cyan-400",
		isFolder: true,
		items: [
			{
				id: "monthly-reports",
				text: "Monthly",
				icon: "calendar-alt",
				iconColor: "text-cyan-400",
				isFolder: false,
				items: [],
			},
			{
				id: "annual-reports",
				text: "Annual",
				icon: "calendar",
				iconColor: "text-teal-400",
				isFolder: false,
				items: [],
			},
			{
				id: "category-breakdown",
				text: "Category Breakdown",
				icon: "chart-pie",
				iconColor: "text-rose-400",
				isFolder: false,
				items: [],
			},
			{
				id: "cashflow",
				text: "Cashflow",
				icon: "chart-area",
				iconColor: "text-indigo-400",
				isFolder: false,
				items: [],
			},
		],
	},
];
